### ISSUE TITLE
[BUG] Errors and deprecated warnings

### ISSUE THREAD

**Issue by fcastilloec** [tfree87/pyRenamer#14]
**Describe the bug**
Some errors and deprecated warnings when running.

**To Reproduce**
Start pyrenamer.py from the command line: `python3 pyrenamer.py`

**Expected behavior**
No errors or warnings should be seen on the command line.

**Screenshots**
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 110, in _builder_connect_callback
    handler, args = _extract_handler_and_args(obj_or_map, handler_name)
  File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 90, in _extract_handler_and_args
    raise AttributeError('Handler %s not found' % handler_name)
AttributeError: Handler on_view1_activate not found
pyrenamer.py:725: DeprecationWarning: Gtk.Action.set_sensitive is deprecated
  self.builder.get_object("menu_rename").set_sensitive(False)
pyrenamer.py:583: DeprecationWarning: Gtk.Window.set_has_resize_grip is deprecated
  self.builder.get_object("main_window").set_has_resize_grip(False)
pyrenamer.py:583: DeprecationWarning: Gtk.Window.set_has_resize_grip is deprecated
  self.builder.get_object("main_window").set_has_resize_grip(False)
pyrenamer.py:1177: Warning: Source ID 45 was not found when attempting to remove it
  removed = GLib.source_remove(i)
```
The last two lines are only shown with different `Source ID` when closing the app via the GUI or just by interacting with the GUI and changing directories or after renaming.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4

**Additional context**
I'm using python 3.8, which is the default for Ubuntu 20.04.4
The app is useable and renaming works without any issues.

I've been looking for a replacement for this app and the only thing I was able to find was a Docker container with the original pyRenamer. I'm very happy to see that you're picking up the development, and very thankful for it. Let me know if there's anything I can do to help. I'm happy to test/try anything you want.

**Comment by tfree87** [comment]
Hi @fcastilloec, thanks for looking into this. I will dig into the GTK documentation to see what the latest (non-deprecated) functions are to see if I can simply replace those calls.
